services:
  db:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_USER: tfgusername
      POSTGRES_PASSWORD: tfgpassword
      POSTGRES_DB: usersdb
    volumes:
      - ./util/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  pgdata:
