services:
  db:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_USER: changeUsername
      POSTGRES_PASSWORD: changePassword
      POSTGRES_DB: users
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - tfg-default-network

networks:
  tfg-default-network:
    driver: bridge

volumes:
  db_data:
