spring:
  kafka:
    ssl:
      trust-store-location: file:/etc/kafka/secrets/certs/kafka.client2.truststore.jks
      trust-store-password: kafkaproduction
      key-store-location: file:/etc/kafka/secrets/certs/kafka.client2.keystore.jks
      key-store-password: kafkaproduction
