spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
      mvc:
        routes:
          - id: user-service
            uri: lb://user-service
            predicates:
              # proxy paths in user service
              - Path=/users/**
              - Path=/activities/**
          - id: request-service
            uri: lb://request-service
            predicates:
              - Path=/generation/**
          - id: init-service
            uri: lb://init-service
            predicates:
              - Path=/init/**
    openfeign:
      oauth2:
        enabled: true
        clientRegistrationId: okta