package com.tdarquier.tfg.code_service.enums;

public enum Template {
    USER_SERVICE_V1,
    CART_SERVICE_V1,
    SHIPPING_SERVICE_V1,
    ORDER_SERVICE_V1,
    NOTIFICATION_SERVICE_V1,
    PRODUCT_SERVICE_V1,
    DISCOVERY_SERVICE_V1,
    GATEWAY_SERVICE_V1,
    CONFIGURATION_SERVICE_V1
}
