services:
  db:
    image: postgres:13
    container_name: product_service_postgres
    environment:
      POSTGRES_USER: changeUsername
      POSTGRES_PASSWORD: changePassword
      POSTGRES_DB: products
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - tfg-default-network

networks:
  tfg-default-network:
    driver: bridge

volumes:
  db_data: