eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
spring:
  kafka:
    ssl:
      protocol: TLSv1.2
    security:
      protocol: "SSL"
    bootstrap-servers: kafka:9093
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: generationRequest:com.tdarquier.tfg.generation_service.kafka.generation.GenerationRequest
      group-id: ssl-consumer #serviceGenerationRequestGroup
      bootstrap-servers: kafka:9093
